name: attendance
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.8.4
  go_router: ^10.0.0
  google_fonts: ^5.1.0
  lottie: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icon/
    - assets/lottie/

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/roboto/Roboto-Thin.ttf
          weight: 200
        - asset: fonts/roboto/Roboto-Light.ttf
          weight: 300
        - asset: fonts/roboto/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/roboto/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/roboto/Roboto-Bold.ttf
          weight: 600
        - asset: fonts/roboto/Roboto-Black.ttf
          weight: 700

    - family: Montserrat
      fonts:
        - asset: fonts/montserrat/Montserrat-Thin.ttf
          weight: 100
        - asset: fonts/montserrat/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: fonts/montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: fonts/montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: fonts/montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: fonts/montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: fonts/montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: fonts/montserrat/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: fonts/montserrat/Montserrat-Black.ttf
          weight: 900

  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
